# Generated by Django 4.1.5 on 2023-02-14 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('document', models.IntegerField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=35)),
                ('last_names', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=40)),
                ('networks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.network')),
            ],
        ),
    ]
