# Generated by Django 4.1.5 on 2023-02-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='networks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_me.network'),
        ),
    ]
