# Generated by Django 4.1.5 on 2023-02-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='id_level_education',
            new_name='level_education',
        ),
    ]
